version: "3.9"

services:
  web:
    build: .
    command: opentelemetry-instrument ./manage.py runserver 0.0.0.0:8000 --noreload
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./config/local.env
    depends_on:
      - db
      - grafana-otel-lgtm

  db:
    image: postgis/postgis:16-3.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./config/local.env
    ports:
      - "5432:5432"

  grafana-otel-lgtm:
    platform: linux/amd64
    image: grafana/otel-lgtm
    container_name: grafana-otel-lgtm
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"

volumes:
  postgres_data:
